spring:
  application:
    name: authentication
  mvc:
    servlet:
      path: /authentication
  datasource:
    url: jdbc:h2:mem:authenticationdb
  h2:
    console:
      enabled: true
  cloud:
    discovery:
      enabled: true

server:
  port: 8081

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
