spring:
  application:
    name: postManagement
  mvc:
    servlet:
      path: /postManagement


server:
  port: 8089

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

