spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: authentication
          uri: lb://authentication # service name
          predicates:
            - Path=/authentication/** # url pattern
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: post
          uri: lb://post
          predicates:
            - Path=/post/**
        - id: postManagement
          uri: lb://postManagement
          predicates:
            - Path=/postManagement/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"

server:
  port: 9000

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
