spring:
  application:
    name: user
  mvc:
    servlet:
      path: /user # // localhost:8087/user/user


server:
  port: 8087

eureka:
  instance:
    hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka

